# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 97a1e5c780eeca8fb2620069a920b307e2b2e6bde41016f6f5a1d228ee3f4f6a4e017fcf9c3a2800ab877f92048d5c0988a1f90e11248b3cd780e5d4f71b3af1

test:
  secret_key_base: 8929dfd49d84c2088cbecdcc38fd1181dfcc505686af6bfe5ae0b05e17de6bb21b871393ccef725a0249569f36db393333e46b69fd9c554ad2931560392bf620

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
